[versions]
# Android SDK
android-minSdk = "24"
android-compileSdk = "36"
android-targetSdk = "36"
# Ktor
ktor-version = "3.4.0"
# Koin
koin-version = "4.1.0"
# Utilities
kotlinx-serialization-json-version = "1.9.0"
# Other
logback-version = "1.5.19"
# Plugins
kotlin-version = "2.3.10"
android-gradle-plugin = "8.13.2"
vanniktech-maven-publish = "0.35.0"
ksp = "2.3.6"
compose-plugin = "1.9.3"

[libraries]
# Ktor Server
ktor-server-core = { module = "io.ktor:ktor-server-core", version.ref = "ktor-version" }
ktor-server-netty = { module = "io.ktor:ktor-server-netty", version.ref = "ktor-version" }
ktor-server-websockets = { module = "io.ktor:ktor-server-websockets", version.ref = "ktor-version" }
# Ktor Client
ktor-client-core = { group = "io.ktor", name = "ktor-client-core", version.ref = "ktor-version" }
ktor-client-cio-jvm = { module = "io.ktor:ktor-client-cio-jvm", version.ref = "ktor-version" }
ktor-client-websockets = { module = "io.ktor:ktor-client-websockets", version.ref = "ktor-version" }
# Serialization
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization-json-version" }
ktor-serialization-kotlinx-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor-version" }
ktor-server-content-negotiation = { module = "io.ktor:ktor-server-content-negotiation", version.ref = "ktor-version" }
ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor-version" }
# Koin
koin-ktor = { module = "io.insert-koin:koin-ktor", version.ref = "koin-version" }
koin-logger-slf4j = { module = "io.insert-koin:koin-logger-slf4j", version.ref = "koin-version" }
koin-test = { module = "io.insert-koin:koin-test", version.ref = "koin-version" }
# Utilities
logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback-version" }
ksp-symbol-processing-api = { module = "com.google.devtools.ksp:symbol-processing-api", version.ref = "ksp" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin-version" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin-version" }
kotlin-plugin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin-version" }
vanniktech-maven-publish = { id = "com.vanniktech.maven.publish", version.ref = "vanniktech-maven-publish" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
kotlin-plugin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin-version" }
jetbrains-compose = { id = "org.jetbrains.compose", version.ref = "compose-plugin" }
android-kotlin-multiplatform-library = { id = "com.android.kotlin.multiplatform.library", version.ref = "android-gradle-plugin" }
android-application = { id = "com.android.application", version.ref = "android-gradle-plugin" }
